### ISSUE TITLE
오류가 나는 atd 파일

### ISSUE THREAD

**Issue by kim-yoonseung** [aqjune/atdtocpp#3]
첨부한 파일에서 transitivity_pointer_lhs라는 타입과 관련되어 오류가 납니다.

이름을 조금만 바꿔도 안 납니다.

확장자만 zip을 붙여서 올립니다.
[input.atd.zip](https://github.com/aqjune/atdtocpp/files/192879/input.atd.zip)

**Comment by aqjune** [comment]
해결했습니다.
