### ISSUE TITLE
.gitignore 에 atdtocpp 추가?

### ISSUE THREAD

**Issue by alxest** [aqjune/atdtocpp#5]
중요한건 아닙니다. 
atdtocpp 바이너리는 다른 파일들에서 만들어지는거고, 사람마다 다르게 나올 수 있으니까 .gitignore 에 추가해놓으면 더 좋을 듯 합니다.
(./build.sh 하고 pull 다시 받으려니까 에러떠서 알게 됨)

**Comment by aqjune** [comment]
요청사항 반영했습니다.
